### ISSUE TITLE
include terms of use and support / source information in download

### ISSUE THREAD

**Issue by alee** [openskope/skopeui#108]
- conditions of use
- who to contact
- provenance / source
- citation #109 
- license (?)

**Comment by kintigh** [comment]
How about this text for these items (in starting the app, in a footer, or in the download ZIP

**Terms of Service**
By using the SKOPE application, you assume any risk associated with its use.  You are solely responsible for any damage or loss you may incur resulting from your reliance on or use of information. provided by SKOPE.

**Citation**
Use of data, graphics, or other information provided by SKOPE should be accompanied by a citation of the original data source (provided iby SKOPE in the dataset metadata) and of the SKOPE application Web page.  Example reference: (SKOPE 2021).
Example Citation:
SKOPE 2021 SKOPE: Synthesizing Knowledge of Past Environments.  https://app.openskope.org/.  Accessed 1 July 2021.

**Contact Us**
Please use the "Email Us" button on the application navigation bar or submit your message directly to  https://www.comses.net/about/contact)

**Comment by alee** [comment]
Looks good to me. 

I think each dataset should declare its own license but I don't see any for LBDA or paleocar at the moment:

Paleocar: https://github.com/bocinsky/paleocar
LBDA: https://data.noaa.gov/dataset/dataset/noaa-wds-paleoclimatology-living-blended-drought-atlas-lbda-version-2-recalibrated-reconstruc
SRTM: I can't seem to find the data page for SRTM, there's a lot of broken links now: https://www2.jpl.nasa.gov/srtm/cbanddataproducts.html

**Comment by kintigh** [comment]
Yes that would be preferable.  If we could identify one key reference for the dataset in the dataset metadata and include both a citation to SKOPE as well as that primary dataset citation that would be ideal. Also I agree that a note recommending that the request.json file be included in supplementary materials in a publication or other documentation of your results would be great for reproduceability.

Keith

______________________________________________________
Keith Kintigh<https://www.public.asu.edu/~kintigh>, Professor Emeritus, Arizona State University<http://asu.edu/> Tempe, USA
Coalition for Archaeological Synthesis<http://archsynth.org/>, Co-President
tDAR<http://tdar.org/> - the Digital Archaeological Record, Co-Chair, Board of Directors
Contact:     505-395-7979(h)     421 Calle Kokopelli, Santa Fe, NM 87501
