### ISSUE TITLE
adjust statistics for the temporal interval series names

### ISSUE THREAD

**Issue by alee** [openskope/skopeui#110]
In the statistics box 

![image](https://user-images.githubusercontent.com/22534/128067872-ed4481db-c4b8-4759-92e4-c4fe74018736.png)

Currently if you apply a z-score transformation + smoothing it sets the "Original" stats line to be the z-score transformation stats and the "Transformed" stats line to be the smoothed z-score stats.

Instead,

- Original statistics should always be for to the original data (not transformed)
- Z-Score should be always be labeled "Transformed"
- add additional "Smoothed" series for the smoothed mean / median

**Comment by kintigh** [comment]
I think we decided Transformed should be labeled transformed but be for the Z Score transformed data and below that add a statistics line for "Smoothed", which is the smoothed Z score data.  That way the terminology is consistent

**Comment by alee** [comment]
implemented in 6edbac59b92f0d99b51721be7012387117345e21 though the original statistics need to be sent back and reported via changes to skope-api https://github.com/openskope/skope-api/issues/16
