### ISSUE TITLE
PaleoCAR reading zero data as NA

### ISSUE THREAD

**Issue by kintigh** [openskope/skopeui#123]
IN PaleoCAR, There is a bug in the routine that was used to read in the data from NOAA that causes GDAL to parse certain data as NA, when it really has values.

I was fooling around with visualize data on SKOPE and happened to click year, 1177.  The selected area is the same as the Chaco Park boundary.  Anyway, this shows that there is lots of missing data for that year right around Chaco, which seems odd since there are a zillion tree rings from Chaco.

**Comment by bocinsky** [comment]
This was an issue with the legend definition and data upload. Fixed!
