### ISSUE TITLE
invalid timespan bounds in paleocar v3

### ISSUE THREAD

**Issue by alee** [openskope/skopeui#132]
![image](https://user-images.githubusercontent.com/22534/131943765-0c4486a7-8f0c-4200-88ff-8737b6b306b1.png)

**Comment by cpritcha** [comment]
This seems to be from a mixture of the user interface requesting requesting year 1CE which doesn't exist and the backend providing some old metadata (`docker-compose down` and `docker-compose up -d` on skope-api seemed to fix the staleness issue). There's also an encoding serialization bug in skope-api to fix for converting to JSON. After that the dataset should be ready.
