### ISSUE TITLE
Make dataset metadata boundary fill transparent

### ISSUE THREAD

**Issue by bocinsky** [openskope/skopeui#149]
The boundary for each dataset has a dark blue boundary and fill opacity set to 0.05. The fill should be transparent in order to not interact with the dataset color scales. It's unclear to me where this is set (it may be the default).

**Comment by alee** [comment]
The dataset bounding rectangle opacity should be set to 0 now as of ec0e36c3715d193fb9dc3201a54fc3390ab034d2
