### ISSUE TITLE
link wms tile layer opacity w/ legend

### ISSUE THREAD

**Issue by alee** [openskope/skopeui#153]
see if there's a way to couple opacity into the GetLegendGraphic request: 

https://docs.geoserver.org/latest/en/user/services/wms/get_legend_graphic/index.html

![image](https://user-images.githubusercontent.com/22534/143115108-c99896e2-3d43-48a5-be7a-397fcdbab7a1.png)

**Comment by bocinsky** [comment]
We'll have to see if the UI refreshes the legend with a change in the opacity...
