### ISSUE TITLE
Y axis Title for Z Score Standardized Data

### ISSUE THREAD

**Issue by kintigh** [openskope/skopeui#155]
When we do a Z-score transformation, the vertical axis label on the graph doesn’t change.  For example its still says “Water Year Precipitation (in mm)”  or whatever.  But the units are no longer mm.  We either need to remove the units all the time (I think just a change in the metadata) and say “Water Year Precipitation” for the graph, whether standardized or not)  or change the Label when the data are Z-Score transformed to say “Water Year Precipitation (Z-Score)”.  I can go either way on that.  It is nice to have the units but having a different label for the Z-Score transformed data may be a bunch more work.

**Comment by alee** [comment]
It's now set to the transform name label (e.g., `ZScore wrt selected interval` or `ZScore wrt fixed interval` etc). I could also include the variable name but then the axis label runs out of space and it gets cut off.

Thoughts?

**Comment by alee** [comment]
mostly fixed in c40791ba0339f7b1e84bf7642ac077ce59244108 - reopen if needed for refinement
