### ISSUE TITLE
Treatment of Datasets with No Timeseries

### ISSUE THREAD

**Issue by kintigh** [openskope/skopeui#156]
I hadn’t tried SRTM 90 lately.  For a small area (Chaco Canyon NHP, attached) I get a timeout on visualize and an error on analyze.  However if I ask for only a single year (from 1000 to 1000) on PMDI or Paleocar I get reasonable behavior--the graph shows at dot at that year (x) and the mean (y) and the statistics show.

This is a bug.  We need to do something to not generate errors.

It may be that we can just assign a year to the SRTM90 dataset and it will no longer be a special case, but perhaps that causes other problems.  If we have to treat it separately, on Visualize just show a map with no graph or a graph with a dot at the mean for that year and for Analyze show the numerical  statistics with no graph or again, a graph with a dot at the mean for that year

**Comment by alee** [comment]
This should be fixed now - needed to set up the right file structure in the skope datasets directory
