### ISSUE TITLE
Restore the Favicon 

### ISSUE THREAD

**Issue by kintigh** [openskope/skopeui#157]
Can we change the Favicon (I think that it what it is called) for the app from what is there now to the one we used on the prototype (it still shows with the prototype app and openskope.org).  That changed somewhere along the line.  here it is.

![SJKOPE_Favicon](https://user-images.githubusercontent.com/11544613/143518044-6eac1717-4081-4642-bb2a-bb11e650c3f1.PNG)
.

**Comment by alee** [comment]
Oops, looks like it broke in an upgrade to nuxt a while back and we never noticed. Thanks for the report!

Fixed in 80cdd22f18c0a0f25e1001a7fc5c7cacb9724101
