### ISSUE TITLE
null values in time series cause client side summary stats to error out

### ISSUE THREAD

**Issue by alee** [openskope/skopeui#158]

**Comment by bocinsky** [comment]
There are drop-in nan-avoiding replacements for `numpy.mean` ([`numpy.nanmean`](https://numpy.org/doc/stable/reference/generated/numpy.nanmean.html)) and `numpy.std` ([numpy.nanstd](https://numpy.org/doc/stable/reference/generated/numpy.nanstd.htmlhttps://numpy.org/doc/stable/reference/generated/numpy.nanstd.html)).

**Comment by alee** [comment]
Unfortunately these stats are still being computed client-side in JavaScript using MathJS 

See https://github.com/josdejong/mathjs/issues/830
