### ISSUE TITLE
Openskope.org website blocked by Firefox and Chrome, 

### ISSUE THREAD

**Issue by kintigh** [openskope/skopeui#164]
the firefox message indicated it may be an expired certificate.

**Comment by alee** [comment]
Ah, thanks for catching that. I'd updated the certificate for staging.openskope.org but the www.openskope.org site is handled by digital antiquity & Jim DeVos and we need to update it there as well. I've reached out to Jim and should have it resolved shortly

**Comment by kintigh** [comment]
Thanks, Allen.

Take care,
Keith


______________________________________________________
Keith Kintigh<https://www.public.asu.edu/~kintigh>, Professor Emeritus, Arizona State University<http://asu.edu/> Tempe, USA
Coalition for Archaeological Synthesis<http://archsynth.org/>, Co-President
tDAR<http://tdar.org/> - the Digital Archaeological Record, Co-Chair, Board of Directors
Contact:     505-395-7979(h)     421 Calle Kokopelli, Santa Fe, NM 87501

**Comment by alee** [comment]
Should be fixed now. Sorry about not checking on that earlier! I'll add it to the checklist for when we need to renew our SSL certificates.

**Comment by kintigh** [comment]
Thanks to you and Jim for talking care of that.  We should think about the longer term solution for that at some point
Keith

______________________________________________________
Keith Kintigh<https://www.public.asu.edu/~kintigh>, Professor Emeritus, Arizona State University<http://asu.edu/> Tempe, USA
Coalition for Archaeological Synthesis<http://archsynth.org/>, Co-President
tDAR<http://tdar.org/> - the Digital Archaeological Record, Co-Chair, Board of Directors
Contact:     505-395-7979(h)     421 Calle Kokopelli, Santa Fe, NM 87501
