### ISSUE TITLE
upgrade to vuetify 2.0

### ISSUE THREAD

**Issue by alee** [openskope/skopeui#17]
https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0#user-content-upgrade-guide

this is a major change, as there are quite a few backwards-incompatible vuetify components that we will need to update - after upgrading the site is completely unusable / degraded in its current form of markup. We should consider if we want to undergo this pain now or kick the can down the road.

As the application is currently not very large I think it's probably best to take the pain now.

**Comment by cpritcha** [comment]
Still todo: add back theme colours
