### ISSUE TITLE
Possible bug in time-series plotly graph.

### ISSUE THREAD

**Issue by kbvernon** [openskope/skopeui#186]
Using PaleoCAR: SW USA Paleoclimate Reconstruction (V3) with the Water-year (Oct-Sep) Precipitation variable and a large polygon over the state of Utah, the time-series graph is not plotting correctly. Just showing a vertical line over the year, rather than the actual (mean?) values.

![image](https://user-images.githubusercontent.com/53311626/189956553-b765b5c4-73b2-4c23-a380-42f22dd7ba77.png)

**Comment by kbvernon** [comment]
Ah. OK. Yeah. I'll make sure to keep the area below that max next time. Thanks!

**Comment by alee** [comment]
closing in favor of #195
