### ISSUE TITLE
units of measure

### ISSUE THREAD

**Issue by kbvernon** [openskope/skopeui#200]
It would be nice if the units of measure were shown in the analyze data section and elsewhere. It's not always obvious without doing some digging. In fact, it doesn't look like V3 states what the units are anywhere. V2 has the units listed, but it's not explicitly stated anywhere that those carry over to V3.

Also, and this is small potatoes in the grand scheme of things, but is it possible to get GDD in Celsius? Maybe a question for @bocinsky? I can't recall off the top of my head if the conversion can be done in the same way as with normal temperature estimates. If not, it would be nice if we could toggle between imperial and metric. 

Thanks!

**Comment by kintigh** [comment]
Thanks very much for the very useful comments. We'll look into resolving them . Keith

________________________________
Keith Kintigh -- Santa Fe, NM
Professor Emeritus, Archaeology
Arizona State University
________________________________
From: Kenneth Blake Vernon ***@***.***>
Sent: Monday, September 11, 2023 1:58:11 PM
To: openskope/skopeui ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [openskope/skopeui] units of measure (Issue #200)


It would be nice if the units of measure were shown in the analyze data section and elsewhere. It's not always obvious without doing some digging. In fact, it doesn't look like V3 states what the units are anywhere. V2 has the units listed, but it's not explicitly stated anywhere that those carry over to V3.

Also, and this is small potatoes in the grand scheme of things, but is it possible to get GDD in Celsius? Maybe a question for @bocinsky<https://urldefense.com/v3/__https://github.com/bocinsky__;!!IKRxdwAv5BmarQ!ZJT8NddJp2UGUluqJtFri2N0hIDXWKHtGiIHgo92ifdH39UzHz_X3RmAaBzaDxkPJng7PR8HYiM9WL5RskGoeyI$>? I can't recall off the top of my head if the conversion can be done in the same way as with normal temperature estimates. If not, it would be nice if we could toggle between imperial and metric.

Thanks!

**Comment by alee** [comment]
Should be addressed in #201 via commits:

https://github.com/openskope/skope-api/commit/245893214578445d7d9b8c6835dc55d5fb050eeb 

and

 https://github.com/openskope/skopeui/commit/0e8186e3d64e59e75780b676cb97e6830583cab6

but need to test in staging for a bit before deploying as there are some underlying dependency upgrades that should be included as well...
