### ISSUE TITLE
renew app.openskope.org ssl cert

### ISSUE THREAD

**Issue by alee** [openskope/skopeui#23]
need to renew ssl certs for *.openskope.org - cert expired on 12/8/2019

app.openskope.orgis causing ERR_CERT_DATE_INVALID errors on skope.comses.net

**Comment by alee** [comment]
currently blocked, waiting to hear back from Digital Antiquity on access to the namecheap registrar.

In order to renew the SSL cert we need to set a DCV CNAME record on namecheap - @tmcphillips do you have access to do this?

**Comment by tmcphillips** [comment]
My rights limited, but I do have permission to add host records to the openskope.org domain.  I have added CNAME records previously. Here is what I see:
![image](https://user-images.githubusercontent.com/3218259/72647208-d732db00-392c-11ea-9ac5-fc4e334b3784.png)

**Comment by alee** [comment]
great, that should be enough.. I sent you an email with the CNAME details, but I think it's ok for it to be public here:

If I understand that screenshot correctly the host should be set to `c281c15c51c1cd71239f85134caa5b2c` and the value field should be set to `c0dba1665693b4912fee3e05100c95c1.7c737f2ecfb040be080dd50ea60eaadf.sectigo.com.` (with the trailing dot)

**Comment by tmcphillips** [comment]
Ok, done, with TTL=Automatic

**Comment by alee** [comment]
oops, I had a copy/paste error @tmcphillips - the hostname should have a leading underscore, `_c281c15c51c1cd71239f85134caa5b2c`

**Comment by tmcphillips** [comment]
ok, how's that?

**Comment by alee** [comment]
that did the trick, thanks! I've got the certs ready now. Would you like to set them up on the openskope nginx server for now and punt on setting up haproxy until next week? They're on the skope server in the `ssl` directory right off the $HOME.

**Comment by alee** [comment]
Will the nginx container do the right thing if I replace the crt and key files in `/projects/skope/openskope.org/` and restart it?

**Comment by alee** [comment]
I updated the crt and key files and restarted the nginx container. Had to reorder the certificates a bit to get nginx to parse them correctly but everything looks to be working again on app.openskope.org and skope.comses.net

As a side note, the Docker setup looks like it could use some tightening at some point. We should be using pinned versions of all base images (e.g., `nginx:stable`) and we could probably replace our custom nginx docker image with an image specified in docker-compose, mounting the appropriate nginx.conf into /etc/nginx/.

I think we could also remove the `prj_cg_skope` user and `USER 0:1258` things; artifacts from the previous system where these were installed.
