### ISSUE TITLE
Transform graph to Z-score relative to period from X to Y

### ISSUE THREAD

**Issue by alee** [openskope/skopeui#34]
Three options for computing the z-score:

1. moving interval (fine as is)
2. selected temporal interval (without years)
3. fixed temporal interval: include a year range, compute the mean + stdev for that year range and compute the z-score based on that mean/stdev for that given year range, not the selected temporal interval

take mean and stdev over the entire series or a window in the series and recast / replot the series in reference

stretch goal: sliding Z-score metric, how is your experience this year related to the cumulative experience across some user-defined window in the series?

**Comment by cpritcha** [comment]
z-score transform options

- use mean and standard deviation for selected years and study area (don't use entire map)
