### ISSUE TITLE
add smoothing functions

### ISSUE THREAD

**Issue by alee** [openskope/skopeui#35]
- [ ] Trailing running average of N years 
- [ ] Centered running average of N years
- [ ] Spline fit to timeseries
- [ ] Kernel density smoothing (lower priority)

Issues:

- moving averages may have incomplete windows of data, response should always have a slot for alerts / messages from the server that could be displayed (e.g., @tako2428 suggests an alert to the user saying "Portions of this window have missing data")

**Comment by cpritcha** [comment]
## Trailing Average (N years)

### Request

```json
{
  "dataset": "paleocar",
  "variable": "paleocar_precipitation",
  "studyArea": {
    "type": "Point",
    "coordinates": [100, 100]
  },
  "timeseries": {
    "yearRange": [5, 10],
    "method": "trailingAverage",
    "width": 7
  }
}
```

### Good Response (200)

```json
{
  "yearRange": [8, 10],
  "timeseries": [103, 105, 106.4]
}
```

Note that the length of the array is shortened to deal with the absence of enough previous year to compute the 7 year trailing average.

### Bad Response (400)

```json
{
  "label": "Study area is too large",
  "detailed": "Selected study of 5.3km2 is larger than max area of 5km2",
}

**Comment by cpritcha** [comment]
## Running Average (N years)

### Request

```json
{
  "dataset": "paleocar",
  "variable": "paleocar_precipitation",
  "studyArea": {
    "type": "Point",
    "coordinates": [100, 100]
  },
  "timeseries": {
    "yearRange": [5, 10],
    "method": "runningAverage",
    "width": 7
  }
}
```

### Good Response (200)

```json
{
  "yearRange": [8, 10],
  "timeseries": [103, 105, 106.4]
}
```

Note that the length of the array is shortened to deal with the absence of enough previous years to compute the 7 year running average.

### Bad Response (400)

```json
{
  "label": "Study area is too large",
  "detailed": "Selected study of 5.3km2 is larger than max area of 5km2",
}

**Comment by cpritcha** [comment]
## Polynomial Spline

### Request

```json
{
  "dataset": "paleocar",
  "variable": "paleocar_precipitation",
  "studyArea": {
    "type": "Point",
    "coordinates": [100, 100]
  },
  "timeseries": {
    "yearRange": [5, 10],
    "method": "smoothingSpline",
    "selection": "generalizedCrossValidation"
  }
}
```

### Good Response (200)

```json
{
  "yearRange": [6, 10],
  "timeseries": [102.4, 105.2, 103, 105, 106.4]
}
```
### Bad Response (400)

```json
{
  "label": "Study area is too large",
  "detailed": "Selected study of 5.3km2 is larger than max area of 5km2",
}

**Comment by cpritcha** [comment]
## Kernel Regression

### Request

```json
{
  "dataset": "paleocar",
  "variable": "paleocar_precipitation",
  "studyArea": {
    "type": "Point",
    "coordinates": [100, 100]
  },
  "timeseries": {
    "yearRange": [5, 10],
    "method": "kernelRegression",
   "submethod": "localLinear",
   "kernel": "epanechnikov",
    "bandwidth": "asymptoticMeanIntegratedSquaredError"
  }
}
```

or


```json
{
  "dataset": "paleocar",
  "variable": "paleocar_precipitation",
  "studyArea": {
    "type": "Point",
    "coordinates": [100, 100]
  },
  "timeseries": {
    "yearRange": [5, 10],
    "method": "kernelRegression",
   "submethod": "localLinear",
   "kernel": "epanechnikov",
    "bandwidth": 2.5
  }
}
```

### Good Response (200)

```json
{
  "yearRange": [6, 10],
  "timeseries": [102.4, 105.2, 103, 105, 106.4]
}
```
### Bad Response (400)

```json
{
  "label": "Study area is too large",
  "detailed": "Selected study of 5.3km2 is larger than max area of 5km2",
}

**Comment by cpritcha** [comment]
## Corner Cases

- how do we handle missing data?

**Comment by cpritcha** [comment]
Here are some sample requests and responses for the time series service. Any thoughts @tmcphillips @bocinsky?

**Comment by cpritcha** [comment]
z-score transform options

- use mean and standard deviation for selected years and study area

**Comment by alee** [comment]
@cpritcha you should put that comment in #34

**Comment by alee** [comment]
centered running average and trailing running averages have been implemented, z-score
