### ISSUE TITLE
landing page year range onblur is updating too soon

### ISSUE THREAD

**Issue by alee** [openskope/skopeui#43]
Steps to reproduce:

1. enter start year 530
2. tab to end year, enter end year 630

as soon as you enter "6" in the end year, it modifies the start year as well

looks like an issue with the input events

**Comment by tako2428** [comment]
Thanks for formalizing this Allen, best, TK

On Jul 24, 2020, at 9:15 AM, A Lee <notifications@github.com<mailto:notifications@github.com>> wrote:



Steps to reproduce:

  1.  enter start year 530
  2.  tab to end year, enter end year 630

as soon as you enter "6" in the end year, it modifies the start year as well

looks like an issue with the input events
