### ISSUE TITLE
refine dataset detail and data visualization UI

### ISSUE THREAD

**Issue by alee** [openskope/skopeui#51]
https://plotly.com/dash/

We don't have the resources to switch to dash now (it was a little too rough around the edges when we were initially evaluating frameworks) but we can still look to their showcases list for inspiration on how to design a better UI for displaying the map + stats. We should select a few exemplar interfaces that we think could be used for the dataset detail page UI and then refactor the SKOPE UI to match.

Showcases: https://dash-gallery.plotly.host/Portal/

Dashboards with maps:

- https://dash-gallery.plotly.host/dash-opioid-epidemic/
- https://dash-gallery.plotly.host/dash-uber-rides-demo/

**Comment by alee** [comment]
@cpritcha suggested we consider building a dedicated visualization page separate from the dataset detail page (the detail page offers the properly parameterized links to get to the visualization page where you can do more detailed stats + data viz)

**Comment by kintigh** [comment]
That sounds like a good ideas to me. It would probably be too complex and cluttered to do it on the existing page

_____________________________________________
Keith Kintigh, 421 Calle Kokopelli, Santa Fe, NM 87501
Prof. Emeritus of Archaeology, Arizona State University

________________________________

**Comment by chrstngyn** [comment]
![overview](https://user-images.githubusercontent.com/8737685/97627163-3491a780-19e8-11eb-9ba8-7f8103812403.png)

![metadata](https://user-images.githubusercontent.com/8737685/97627180-39eef200-19e8-11eb-826e-2788ff4f07f8.png)

![stats](https://user-images.githubusercontent.com/8737685/97627190-3f4c3c80-19e8-11eb-8369-4ad35d142720.png)

**Comment by alee** [comment]
## Notes from the 2020-11-04 call
Attendees: Ann, Keith, Andrew, Keith, Christine, Calvin, Allen

- landing page can remain mostly the same
- clicking on a dataset brings up a visible workflow

`Select Dataset <-> Define Study Area <-> Animate Map <-> Visualize Data <-> View Metadata`

### Define Study Area

focused on just entering / editing / saving / importing the spatial context

- consider allowing latlong entry
- remove all other controls (opacity, temporal range, variable layer selection)
- include the basic metadata (variables, basic description listed in 

### Animate Map
in `Animate Map` we should see the time series graph as well so we can see the spatial variability alongside the timeseries data

- include opacity control, temporal range (display only), variable layer selection
- replace temporal range slider with the timeseries itself as the control to change the selected year which changes the layer on the map. Likewise, animation should modify the selected year in the timeseries data (need to check feasibility of this)
- remove options to adjust the study area (download geojson still available?)

### Visualize Data

- work out what statistics should be displayed, no need to display the study area as a map anymore (from @kintigh)
- display the study area's area (sq km), selected variable and basic metadata (e.g., Palmer Modified Drought Index), temporal range. Allow changes to temporal range

### View Metadata

- display all detailed metadata, and eventually provenance #18 #48

**Comment by cpritcha** [comment]
Ability to click anywhere on a plotly plot to add lines https://github.com/plotly/plotly.js/pull/5138

**Comment by chrstngyn** [comment]
Hi everyone,

I'll update the mockups and attach them to this issue thread by Thursday

https://www.figma.com/file/jSJtUnNQcWvOjqa20PUyc9/Data-Viz-UI?node-id=4%3A0

**Comment by kintigh** [comment]
Great, thanks.
Keith


__________________________________________________________
Keith Kintigh<Keith%20Kintigh>, Professor Emeritus, Arizona State University<http://asu.edu/> Tempe, USA
Coalition for Archaeological Synthesis<http://archsynth.org/>, Co-President
tDAR<http://tdar.org/> - the Digital Archaeological Record, Co-Chair, Board of Directors
Contact:     505-395-7979(h)     421 Calle Kokopelli, Santa Fe, NM 87501

**Comment by kintigh** [comment]
Christine

This is looking good.  Thank you.  A few suggestions.

**Navigation at the top.**  Also, I think people need to select a dataset and define a study area, but after that they may go straight to the visualize screen and may look at the metadata at any point.   I think I would leave off the numbers off the 5 options.  I think this looks more linear than it needs to.  Would these be better as tabs?

**Define Study Area.** I think we want this screen to be dominated by the map.  I know that I suggested having the basic metadata here, but I wonder if there is a way to fit it in in a way that allows the map to be much bigger, or maybe it is better not to have the metadata at all.  People can easily click on the metadata navigation button and come right back, right?   Do we need the **Animate Map** button on the bottom?  It takes space and I think we can rely on the navigation to the top. 
 
**Animate Map.**  Here again we want the map to dominate.  The graph needs to be much smaller.  I am not sure we need the variables listed separately from the layers.   Also, I don't think we need the dataset description or **download chart** on this page the latter will be on the visualize pages.  The date range selection  needs to be really obvious. We need to be able easily to type in a begin and end date for the sequence (though if it can be done nicely letting people know what the extreme begin and end dats for the series are.  I think the current year can bounce along the graph and doesn’t need a separate line.  I defintely don't think we need the study area size here.  I'm not sure that needs to be anywhere except the define study area page.

**Metadata.**  I think I would also include the paragraph and variable list and description that you have on the define study area page so one sees everything together.

I’m not sure what the **Source** button does--on several pages

Thanks for your good work on this,
Keith

**Comment by chrstngyn** [comment]
> **Navigation at the top.** Also, I think people need to select a data set and define a study area, but after that they may go straight to the visualize screen and may look at the metadata at any point. I think I would leave off the numbers off the 5 options. I think this looks more linear than it needs to. Would these be better as tabs?

I can omit numbers so that it is less linear, but I can understand why it can be confusing. I can implement the top navigation without numbers, and people can test out the navigation and see how they feel. If people prefer tabs after testing than I can certainly implement tabbed navigation instead.

> **Define Study Area.** I think we want this screen to be dominated by the map. I know that I suggested having the basic metadata here, but I wonder if there is a way to fit it in in a way that allows the map to be much bigger, or maybe it is better not to have the metadata at all. People can easily click on the metadata navigation button and come right back, right? Do we need the **Animate Map** button on the bottom? It takes space and I think we can rely on the navigation to the top.

I will remove the Animate Map button at the bottom. I added it to give the user two options of navigating through the process, but I think it is OK if the top nav is the only method of navigation.

> **Animate Map.** Here again we want the map to dominate. The graph needs to be much smaller. I am not sure we need the variables listed separately from the layers. Also, I don't think we need the dataset description or **download chart** on this page the latter will be on the visualize pages. The date range selection needs to be really obvious. We need to be able easily to type in a begin and end date for the sequence (though if it can be done nicely letting people know what the extreme begin and end dats for the series are. I think the current year can bounce along the graph and doesn’t need a separate line. I defintely don't think we need the study area size here. I'm not sure that needs to be anywhere except the define study area page.
>
> **Metadata.** I think I would also include the paragraph and variable list and description that you have on the define study area page so one sees everything together.

I can make changes to the mockups so they reflect the changes you suggested.

> I’m not sure what the **Source** button does--on several pages

The source button condenses the information that is currently displayed as Source: http://srtm.csi.cgiar.org, but I can reverse this design change if it is clearer to display the full link to the source of the dataset.

**Comment by kintigh** [comment]
This sounds good.  Thank you.

On the source button, I am not sure we need that all these places as long as it is on the detailed metadata page.  I understand having multiple ways to get things but I think that just adds complexity to the screen and if people wanted that they would go to the metadata page.  If others disagree they should speak up.

Keith


__________________________________________________________
Keith Kintigh<Keith%20Kintigh>, Professor Emeritus, Arizona State University<http://asu.edu/> Tempe, USA
Coalition for Archaeological Synthesis<http://archsynth.org/>, Co-President
tDAR<http://tdar.org/> - the Digital Archaeological Record, Co-Chair, Board of Directors
Contact:     505-395-7979(h)     421 Calle Kokopelli, Santa Fe, NM 87501

**Comment by alee** [comment]
Notes from December 9th call:

Attendees: Christine, Calvin, Keith, Kyle, Andrew, Allen

- replace numbered steps on navigation with appropriate icons since there's no real order besides the preconditions of Select Dataset and Define a Study Area

1. Define Study Area should only have the map + dataset title
2. Remove `View Metadata` step and replace with a View Metadata button next to the dataset title on every subsequent page after `Select Dataset` that brings up a modal with the detailed dataset metadata
3. Add universal input controls to all subsequent pages after `Select Dataset` select variable of interest e.g., Growing Degree Days (F, May-Sept), Precipitation Water-year (Oct-Sept) Precipitation (mm), Crop Niche Maize Farming Niche (Direct Precip.) #55

**Comment by alee** [comment]
Notes from December 18th call:

Attendees: Christine, Calvin, Keith, Kyle, Andrew, Ann, Allen, Tim

- in Define Study Area, switch to two column layout to maximize the map space which should be closer to a square than a long rectangle as it was. Place map in e.g. 9 columns and basic metadata / opacity slider in the other 3 sliders. Remove temporal range. Show basic dataset boundaries rectangle
- reduce footer size by putting all text + github etc together in the footer
- in analysis screen there should be some clear description of how the defined study area is pulling data from the dataset, whether it is crossing pixel boundaries etc. 
- anything else I missed? Please feel free to edit this issue! I was distracted towards the end of the call by an errant bird. Seriously..

**Comment by alee** [comment]
Notes from Jan 15th call:

Attendees: Keith, Andrew, Tim K, Kyle, Calvin, Christine, Allen, Bertram

### Stepper nav component

- clearly highlight the current step and distinguish between the previously performed steps

### Define Study Area Step

@chrstngyn 

- add confirmation step before loading persisted study area geometry
- remove legend and variable layers control from map
- continue to reduce unnecessary whitespace and make map larger if possible
- make map take up all the space, responsive to always be full height and remove metadata side column. This means we need to add the Variables and any other missing contextual metadata back into the `View Metadata` modal
- have a 'Next' button floated right of the title to move from `Define Study Area` -> `Visualize Data` that is disabled until an appropriate study area has been defined
- should also prevent getting to Visualize Data until a study area has been defined
- look into ways to programmatically validate appropriate study areas for a given dataset @bocinsky 

### Visualize Data Step

@cpritcha 

- add temporal range (min/max year) as a bottom control of the Time Series
- add Year to the title bar of Map and Time Series
- switch to variable name, not class
- remove layers control for switching variables in the map
- move Export step into an Export button on the Time Series title bar
- consider how to make post-processing explicit and include what steps were done

### Analyze / Smooth Data Step (new)

- map goes away, Time Series takes full width and offers form controls on a smaller sidebar on the right to select various statistics and smoothing functions etc.
- change Export step into Analyze step that includes the smoothing functions etc., that also has an Export / Download action
- replaces Export step
- offer the option to download all the statistical analyses selected instead of toggling them one at a time and downloading them individually

**Comment by alee** [comment]
Notes from full meeting:

- highlight the active step more
- look into moving the stepper into the topmost navbar
- be consistent in language (geometry vs selected area)
- Restyle the variable input control and make it more clear that it is where you can change the variables. Add `Variable: ` to variable input select dropdown on the bottom right of the Map
- When there is only one variable layer to be displayed, select it by default (as it appears to be working now) and set input variable in controls #55
- In contrast, when there is more than one variable layer available add a "select a variable" option to the options and do not select the first variable by default
