### ISSUE TITLE
analyze page: support page refresh properly

### ISSUE THREAD

**Issue by alee** [openskope/skopeui#69]
Refreshing the analyze page will cause a bug since there is no default variable selected and it requires a variable to be analyzed.

Possible solutions:

1. push variable id into the URL
2. store variable in local storage like the geometry
3. return a default variable if none is selected (like the visualize route)

Leaning towards the URL solution as it's more straightforward / self documenting but as a first cut the default variable is simplest to implement

**Comment by chrstngyn** [comment]
For the route solution, we could refer to Vue's documentation for using navigation guards

https://router.vuejs.org/guide/advanced/navigation-guards.html#global-before-guards

**Comment by chrstngyn** [comment]
Every time a variable is selected, the query param updates and show in the URL. We still need to grab the variable.id from the route's query param to programmatically generate the same query.variable.id to set the variable on a refresh, which the link above on navigation guards could be helpful for. Navigating between pages without a page refresh works fine.
