### ISSUE TITLE
refresh on Select Area or Visualize Data breaks subsequent routing

### ISSUE THREAD

**Issue by alee** [openskope/skopeui#72]
refreshing a page is breaking routing somehow. Steps to reproduce:

1. at Select Area page hit refresh
2. click on Visualize Data
3. nothing happens but the URL changes to `datasetId/visualize`
4. going back and forth between visualize and select area does nothing
5. same thing happens if you refresh in Visualize Data and go into Select Area

Things get fixed if you go all the way back out to Select Dataset

**Comment by chrstngyn** [comment]
- refresh of page breaks the application
- when observing components in Vue dev tools, on a page refresh, components are not rendering and don't seem to be initializing properly
- Visualize component disappears from Vue dev tools when you try to click on another step after refresh

before refresh:
![image](https://user-images.githubusercontent.com/8737685/114633269-14dbfc00-9c75-11eb-818d-19f534583c9e.png)

after refresh and after clicking on another step in attempt to navigate to another page:
![image](https://user-images.githubusercontent.com/8737685/114633356-3806ab80-9c75-11eb-95aa-bac2e0a20a65.png)

**Comment by chrstngyn** [comment]
https://stackoverflow.com/questions/47862591/vuejs-error-the-client-side-rendered-virtual-dom-tree-is-not-matching-server-re

https://vuejs.org/v2/guide/conditional.html#v-if-vs-v-show

perhaps we could try replacing v-if with v-show

**Comment by chrstngyn** [comment]
![image](https://user-images.githubusercontent.com/8737685/115064727-2229fe00-9ea2-11eb-9bb5-64964d79ce43.png)

**Comment by chrstngyn** [comment]
https://blog.lichter.io/posts/vue-hydration-error/
