### ISSUE TITLE
add analyze form input helpers 

### ISSUE THREAD

**Issue by chrstngyn** [openskope/skopeui#76]
Pictured below is the UI for the analyze page which includes a map and analysis form. Next to reach of the analysis inputs, there is a question mark which users can hover over to reveal more information. Could you provide some text I can add hints to these question mark elements next to the analysis form inputs?

@kintigh @bocinsky 

![image](https://user-images.githubusercontent.com/8737685/116134608-f3bbd800-a684-11eb-9f55-72ba2410286c.png)

**Comment by kintigh** [comment]
Traveling today. Will do tomorrow or Wednesday

_____________________________________________
Keith Kintigh, 421 Calle Kokopelli, Santa Fe, NM 87501
Prof. Emeritus of Archaeology, Arizona State University

________________________________
From: Christine Nguyễn ***@***.***>
Sent: Monday, April 26, 2021 2:46:52 PM
To: openskope/skopeui ***@***.***>
Cc: Keith Kintigh ***@***.***>; Mention ***@***.***>
Subject: [openskope/skopeui] add analyze form input helpers (#76)


Pictured below is the UI for the analyze page which includes a map and analysis form. Next to reach of the analysis inputs, there is a question mark which users can hover over to reveal more information. Could you provide some text I can add hints to these question mark elements next to the analysis form inputs?

@kintigh<https://urldefense.com/v3/__https://github.com/kintigh__;!!IKRxdwAv5BmarQ!NCyZG6UUoRLYV6KrANAossax8qf6GPu3eyARUmXcFFgF4QoTmd-_Sio0R44Py4ibskgt4Q$> @bocinsky<https://urldefense.com/v3/__https://github.com/bocinsky__;!!IKRxdwAv5BmarQ!NCyZG6UUoRLYV6KrANAossax8qf6GPu3eyARUmXcFFgF4QoTmd-_Sio0R44Py4hZ5NQ0VQ$>

[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/8737685/116134608-f3bbd800-a684-11eb-9f55-72ba2410286c.png__;!!IKRxdwAv5BmarQ!NCyZG6UUoRLYV6KrANAossax8qf6GPu3eyARUmXcFFgF4QoTmd-_Sio0R44Py4j84zx_Zw$>

**Comment by kintigh** [comment]
Christine et al.

I have written some documentation organized based on the great looking Analysis screen you provided.  I think you can extract pieces pf this for the information buttons you have included.

Other comments and revisions welcome, of course.

Keith
______________________________________________________
Keith Kintigh<https://www.public.asu.edu/~kintigh>, Professor Emeritus, Arizona State University<http://asu.edu/> Tempe, USA
Coalition for Archaeological Synthesis<http://archsynth.org/>, Co-President
tDAR<http://tdar.org/> - the Digital Archaeological Record, Co-Chair, Board of Directors
Contact:     505-395-7979(h)     421 Calle Kokopelli, Santa Fe, NM 87501


From: Christine Nguyễn ***@***.***>
Sent: April 26, 2021 2:47 PM
To: openskope/skopeui ***@***.***>
Cc: Keith Kintigh ***@***.***>; Mention ***@***.***>
Subject: [openskope/skopeui] add analyze form input helpers (#76)


Pictured below is the UI for the analyze page which includes a map and analysis form. Next to reach of the analysis inputs, there is a question mark which users can hover over to reveal more information. Could you provide some text I can add hints to these question mark elements next to the analysis form inputs?

@kintigh<https://urldefense.com/v3/__https:/github.com/kintigh__;!!IKRxdwAv5BmarQ!NCyZG6UUoRLYV6KrANAossax8qf6GPu3eyARUmXcFFgF4QoTmd-_Sio0R44Py4ibskgt4Q$> @bocinsky<https://urldefense.com/v3/__https:/github.com/bocinsky__;!!IKRxdwAv5BmarQ!NCyZG6UUoRLYV6KrANAossax8qf6GPu3eyARUmXcFFgF4QoTmd-_Sio0R44Py4hZ5NQ0VQ$>

[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/8737685/116134608-f3bbd800-a684-11eb-9f55-72ba2410286c.png__;!!IKRxdwAv5BmarQ!NCyZG6UUoRLYV6KrANAossax8qf6GPu3eyARUmXcFFgF4QoTmd-_Sio0R44Py4j84zx_Zw$>
