### ISSUE TITLE
refine temporal range update functionality

### ISSUE THREAD

**Issue by alee** [openskope/skopeui#88]
In the analysis page the double update buttons are confusing: updating the time series plot's temporal range and the transformation options. Would be nice to have both update each other so clicking on "Update" in the analysis stats form applies the pending temporal range from the time series plot.

see if we can update the time series when the time series plot's temporal range changes (onblur). If so, replace the manual "enter" event handling with it

**Comment by chrstngyn** [comment]
keydown.enter on upper bound value throws too much recursion error

**Comment by chrstngyn** [comment]
keydown-enter on lower bound value throw too much recursion error if I attempt to enter a lower bound value for the second time

**Comment by chrstngyn** [comment]
8d635e6d06fdfaa82c22fce341771e7b3faffac0 adds a hint property to the v-text-field inputs for the lower and upper bound values. The hint guides the user to click enter to submit their inputs

**Comment by chrstngyn** [comment]
recursion error moved to separate issue #91

**Comment by chrstngyn** [comment]
in addition to press enter, onblur was added in 7dc4d18b5315a1a47285fb9269329e0eb496523a
