### ISSUE TITLE
improve download

### ISSUE THREAD

**Issue by alee** [openskope/skopeui#92]
- [ ] timeseries data should be included as CSV (long form is easier e.g., `dataset, timeseries name, x, y` or something along those lines)
- [x] include plot as a PNG file as well as SVG
- [x] downloads not working for some on Safari and Chrome (possible JS issue?)
- [x] include metadata file with the dataset name, variable selected, time range summary statistic, smoothing / transformation options, area definition in some obvious format (or a URL with short hash e.g., #18)

**Comment by chrstngyn** [comment]
PNG export added in  a40fbe80f4135258bd0e737da42719595782d595

**Comment by chrstngyn** [comment]
safari compatibility resolved in 114f18a701624a467005dc6b5e14dc10d73e9b36
